### ISSUE TITLE
Unable to run toasting.py

### ISSUE THREAD

**Issue by Caz3mir** [imchipwood/Toasting#1]
Hello. I am unable to run toasting.py after about a week of installing all the stuff needed including wxpython wich takes a few hours to compile and totally freezes my Rpi.
Here is the error i get:

`pi@raspberry:~/Desktop/bga/Toasting-master $ sudo python3 toasting.py
/usr/local/lib/python3.8/site-packages/wx/lib/pubsub/__init__.py:23: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  warnings.warn('wx.lib.pubsub has been deprecated, plese migrate your '
Traceback (most recent call last):
  File "toasting.py", line 12, in <module>
    view = ToastingGUI(
  File "/home/pi/Desktop/bga/Toasting-master/library/ui/ToastingGUI.py", line 34, in __init__
    ToastingBase.__init__(self, parent)
  File "/home/pi/Desktop/bga/Toasting-master/library/ui/ToastingGUIBase.py", line 405, in __init__
    progressSizer.Add( self.progressGauge, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ALL|wx.EXPAND, 0 )
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at /tmp/pip-install-a557iyl4/wxpython/ext/wxWidgets/src/common/sizer.cpp(2089) in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND
pi@raspberry:~/Desktop/bga/Toasting-master $ 
`

**Comment by imchipwood** [comment]
What version of wxPython did you install? The error seems to be related to the syntax/arguments expected between different versions

**Comment by imchipwood** [comment]
Also, try the modularize branch. I have no idea what the state of the master branch is.

**Comment by Caz3mir** [comment]
> What version of wxPython did you install? The error seems to be related to the syntax/arguments expected between different versions
I used wxpython 4.1.0 and about all the latest packages i could find. This has taken me about a week with having to compile wx for 2 machines i tested it on and culminating with today getting the same error on rpi3 as on the first desktop pi i tried for faster compile speed.
I have emailed you but got no answer, is there any way we can get in touch about this project?
Thanks in advance

**Comment by imchipwood** [comment]
I'm not interested in commercializing this project, nor do I have much time to devote to fixing any issues. I run it on an rpi3 and haven't used it in over a year - yes, setting it up was a pain because of wxPython but at the time, that's the GUI package I was using at work so I was familiar with it. 

I spent a little time trying to create a web UI using JS so the RPI could act as a server and any web-enabled device could interface with it, but I quickly learned that I hate web development and dropped that project.

Anyway, I can't really offer much help - this project is mostly hosted on GitHub as an example and was never really intended to be polished to perfection. If I find some time to set my oven back up and try the code, I'll let you know.

**Comment by imchipwood** [comment]
Hey,

I finally had a reason to break out my reflow oven again, so I worked through the issues getting this up and running on a fresh Raspbian install on a Pi 3B+. The master branch has all of my updates. Note that I force pushed onto the master branch since I didn't feel like working through the conflicts.

Updates I made:

* Now uses wxpython==4.1.1, which is available as a wheel in pypi (no need to compile!)
* Also updated matplotlib & numpy and worked through some issues from those updates - namely stuff in matplotlib

Eventually I'd like to refactor most of this project as it's not PEP8 compliant at all, and I really hate running the UI on the Raspberry Pi (requires a monitor or a VNC connection). That's unlikely to happen any time soon...


-Chip
